/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FORM_MAIN_APP.java
 *
 * Created on Jan 22, 2012, 2:16:16 PM
 */
package com.zisal.fsaapplication;

import java.awt.event.ActionEvent;
import java.util.Arrays;
import java.util.Vector;
import javax.print.DocFlavor.INPUT_STREAM;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author fauzi
 */
public class FORM_MAIN_APP extends javax.swing.JFrame {

    /** Creates new form FORM_MAIN_APP */
    public FORM_MAIN_APP() {        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    JLabel lbltrans;
    JTextField txttrans1;
    JTextField txttrans2;
    JTable table;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelVarUtama = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtQ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        panelTransisi = new javax.swing.JPanel();
        btGenerate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cekFSA = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Simulasi FSA");

        jLabel1.setText("M = (Q, E, V, S, F)");

        javax.swing.GroupLayout panelJudulLayout = new javax.swing.GroupLayout(panelJudul);
        panelJudul.setLayout(panelJudulLayout);
        panelJudulLayout.setHorizontalGroup(
            panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
            .addGroup(panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelJudulLayout.createSequentialGroup()
                    .addGap(0, 131, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 131, Short.MAX_VALUE)))
        );
        panelJudulLayout.setVerticalGroup(
            panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
            .addGroup(panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelJudulLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panelJudul, java.awt.BorderLayout.PAGE_START);

        panelVarUtama.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setText("Q = ");
        panelVarUtama.add(jLabel2);
        panelVarUtama.add(txtQ);

        jLabel3.setText("E = ");
        panelVarUtama.add(jLabel3);
        panelVarUtama.add(txtE);

        jLabel4.setText("V = ");
        panelVarUtama.add(jLabel4);
        panelVarUtama.add(txtV);

        jLabel5.setText("S = ");
        panelVarUtama.add(jLabel5);
        panelVarUtama.add(txtS);

        jLabel6.setText("F = ");
        panelVarUtama.add(jLabel6);
        panelVarUtama.add(txtF);

        getContentPane().add(panelVarUtama, java.awt.BorderLayout.CENTER);

        panelTransisi.setLayout(new java.awt.BorderLayout());

        btGenerate.setText("Generate");
        btGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerateActionPerformed(evt);
            }
        });
        panelTransisi.add(btGenerate, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panelTransisi, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("File");

        cekFSA.setText("Cek FSA");
        cekFSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekFSAActionPerformed(evt);
            }
        });
        jMenu1.add(cekFSA);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("Cek Inputan");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String [][] data=new String[20][20];    
    /*public void getData(){        
        for(int a=0;a<getIsiQ().length;a++){
            for(int b=0;b<getIsiE().length;b++){
                data[a][b]=txttrans.getText();
                JOptionPane.showMessageDialog(null, "isi = "+data[a][b]);
            }
        }
    }*/
    public void Generate(){                
   /*     String[] lblbaru=getIsiQ();
        for(int a=0;a<getIsiE().length;a++){
            JFrame formTransisi=new JFrame();            
            formTransisi.setTitle(getIsiE()[a]);
            formTransisi.setSize(200,200);
            formTransisi.setLayout(new java.awt.GridLayout(getIsiQ().length+1, getIsiE().length));
            formTransisi.setVisible(true);
            for(int b=0;b<getIsiQ().length;b++){                
                lbltrans=new JLabel(lblbaru[b]);                
                txttrans1=new JTextField("");
                formTransisi.getContentPane().add(lbltrans);
                formTransisi.getContentPane().add(txttrans1);
                formTransisi.setVisible(true);                
            }                                    
            JButton btKirim=new JButton("oke");
            formTransisi.getContentPane().add(btKirim);
            btKirim.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btkirimActionPerformed(e);
                }
               
            });
        }*/
            JFrame formTransisi=new JFrame();            
            formTransisi.setTitle("Form Transisi");
            formTransisi.setSize(300,400);
            formTransisi.setLayout(new java.awt.BorderLayout());
            formTransisi.setLocationRelativeTo(null);
            formTransisi.setVisible(true);        
            String [] row=getIsiQ();            
            Vector rowData = new Vector();
            for (int i = 0; i < getIsiQ().length; i++) {
                Vector colData = new Vector(Arrays.asList(row[i]));
                rowData.add(colData);
            }
            String [] columnNames=new String[getIsiE().length+1];
            columnNames[0]="V";
            String [] getisiisiE=getIsiE();
            for(int a=1;a<=getIsiE().length;a++){
                columnNames[a]=getisiisiE[a-1];
            }
            Vector columnNamesV = new Vector(Arrays.asList(columnNames));
            table = new JTable(rowData, columnNamesV);
            formTransisi.getContentPane().add(new JScrollPane(table));
    }
    int tam=-1;
    private void btkirimActionPerformed(ActionEvent e) {
        tam++;
//        data[tam][0]=txttrans.getText();
    }
    private void btGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateActionPerformed
        // TODO add your handling code here:
        Generate();
    }//GEN-LAST:event_btGenerateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    public boolean  cekFSA(){        
        boolean oke=false;//DFA
        String [] dataCek=new String[20];
            for(int b=0;b<getIsiQ().length;b++){
             for(int a=1;a<=getIsiE().length;a++){                
                 String pengecekan=String.valueOf(table.getValueAt(b, a));                                  
                 if(pengecekan.length()>2 || pengecekan.length()==0){
                     oke=true;
                 }
                 else{
                     oke=false;
                 }
             }   
            }            
            JOptionPane.showMessageDialog(null, oke);
        return oke;
    }
    private void cekFSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekFSAActionPerformed
        // TODO add your handling code here:
//        getData();
        cekFSA();
        if(cekFSA()==true){
            JOptionPane.showMessageDialog(null, "FSA = NFA","informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "FSA = DFA","informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cekFSAActionPerformed
public String getQ(){
    return txtQ.getText();
}
public String getE(){
    return txtE.getText();
}
public String getV(){
    return txtV.getText();
}
public String getS(){
    return txtS.getText();
}
public String getF(){
    return txtF.getText();
}
public String [] getIsiQ(){
    String isi=getQ();
    String [] isinyaQ =new String[20];
    isinyaQ=isi.split(" ");
    return isinyaQ;
}
public String [] getIsiE(){
    String isi=getE();
    String [] isinyaE=new String[20];
    isinyaE=isi.split(" ");
    return isinyaE;
}
public String [] getIsiF(){
    String isi=getF();
    String [] isinyaF=new String[20];
    isinyaF=isi.split(" ");
    return isinyaF;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FORM_MAIN_APP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGenerate;
    private javax.swing.JMenuItem cekFSA;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JPanel panelTransisi;
    private javax.swing.JPanel panelVarUtama;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtQ;
    private javax.swing.JTextField txtS;
    private javax.swing.JTextField txtV;
    // End of variables declaration//GEN-END:variables
}
