package com.zisal.konversibilangandigital;


import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bil_dig_form.java
 *
 * Created on Jan 30, 2011, 8:38:59 AM
 */

/**
 *
 * @author FAUZI
 */
public class bil_dig_form extends javax.swing.JFrame {

    /** Creates new form bil_dig_form */
    public bil_dig_form() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtmasuk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmboperasi = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btkonversi = new javax.swing.JButton();
        txthasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KONVERSI BILANGAN SISTEM DIGITAL");

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("PILIH JENIS OPERASI :");

        cmboperasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BINER KE DESIMAL", "DESIMAL KE BINER", "HEKSADESIMAL KE BINER", "OKTAL KE BINER", "HEKSADESIMAL KE OKTAL" }));

        jLabel2.setText("MASUKKAN BILANGAN :");

        btkonversi.setText("Konversi");
        btkonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkonversiActionPerformed(evt);
            }
        });

        jLabel3.setText("HASIL :");

        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(btreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btkonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txthasil, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmasuk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmboperasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmboperasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btkonversi)
                    .addComponent(btreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btkonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkonversiActionPerformed
String masuk=txtmasuk.getText();
int length=masuk.length();
int des=0,a,hasil=0,mod,sisa;
String bin="";

if(cmboperasi.getSelectedItem()=="BINER KE DESIMAL"){         
   for(a=0;a<=length-1;a++){
    if(masuk.charAt(a)=='1'){
    hasil+=pangkat(2,length-1-a);    
   }
 else if(masuk.charAt(a)=='0'){
     hasil+=0;
 }
   }
   txthasil.setText(String.valueOf(hasil));
}
if(cmboperasi.getSelectedItem()=="DESIMAL KE BINER"){
    int masuk2=Integer.parseInt(masuk);    
    hasil=masuk2/2;
    do{
        mod=masuk2%2;
        if(mod==0){
            bin+="0";
        }
 else if(mod==1){
     bin+="1";
      }        
        masuk2=hasil;
        hasil=masuk2/2;
    }
    while(hasil>=1);
    txthasil.setText("1"+bin);
        }
if(cmboperasi.getSelectedItem()=="HEKSADESIMAL KE BINER"){
    int arti=0;
    sisa=0;
    hasil=0;
    for(a=0;a<=length-1;a++){
        if(masuk.charAt(a)=='A' ||masuk.charAt(a)=='a'){
        arti=10;
        des+=arti*pangkat(16,length-1-a);        
        }
        else if(masuk.charAt(a)=='B' ||masuk.charAt(a)=='b'){
        arti=11;
        des+=arti*pangkat(16,length-1-a);
        }
        else if (masuk.charAt(a) == 'C' || masuk.charAt(a) == 'c') {
        arti=12;
        des+=arti*pangkat(16,length-1-a);
        }
        else if (masuk.charAt(a) == 'D' || masuk.charAt(a) == 'd') {
        arti=13;
        des+=arti*pangkat(16,length-1-a);        
        }
        else if (masuk.charAt(a) == 'E' || masuk.charAt(a) == 'e') {
        arti=14;
        des+=arti*pangkat(16,length-1-a);        
        }
        else if (masuk.charAt(a) == 'E' || masuk.charAt(a) == 'e') {
        arti=15;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='1') {
            arti=1;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='2') {
            arti=2;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='3') {
            arti=3;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='4') {
            arti=4;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='5') {
            arti=5;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='6') {
            arti=6;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='7') {
            arti=7;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='8') {
            arti=8;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='9') {
            arti=9;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) == '0') {
        des+=0;
        }       
    }            
     //konversi KE Biner
        hasil=des/2;
        do{
            sisa=des%2;
            if(sisa==1){
                bin+="1";
            }
            else if(sisa == 0)
            {
                bin+="0";
            }
            des=hasil;
            hasil=des/2;
        }
        while(hasil>=1);
        txthasil.setText("1"+bin);
}
if(cmboperasi.getSelectedItem()=="OKTAL KE BINER"){
//konversi ke desimal
    for(a=length-1;a>=0;a--){
        if(masuk.charAt(a)=='1'){
        des+=pangkat(8,length-a-1) ;
        }
        if(masuk.charAt(a)=='0'){
        des+=0;
        }
    }
JOptionPane.showMessageDialog(null,"desimal = "+des);
//konversi ke biner
sisa=0;
hasil=0;
hasil=des/2;
bin="";
JOptionPane.showMessageDialog(null,"hasilbagi ="+ hasil);
do{
sisa=des%2;
    if(sisa==1){
        bin+="1";
    }
    if(sisa==0)
    {
        bin+="0";
    }
des=hasil;
hasil=des/2;
}
while(hasil>=1);
txthasil.setText("1"+bin);
}
if(cmboperasi.getSelectedItem()=="HEKSADESIMAL KE OKTAL"){
    int arti=0;
    sisa=0;
    hasil=0;
    for(a=0;a<=length-1;a++){
        if(masuk.charAt(a)=='A' ||masuk.charAt(a)=='a'){
        arti=10;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a)=='B' ||masuk.charAt(a)=='b'){
        arti=11;
        des+=arti*pangkat(16,length-1-a);
        }
        else if (masuk.charAt(a) == 'C' || masuk.charAt(a) == 'c') {
        arti=12;
        des+=arti*pangkat(16,length-1-a);
        }
        else if (masuk.charAt(a) == 'D' || masuk.charAt(a) == 'd') {
        arti=13;
        des+=arti*pangkat(16,length-1-a);
        }
        else if (masuk.charAt(a) == 'E' || masuk.charAt(a) == 'e') {
        arti=14;
        des+=arti*pangkat(16,length-1-a);
        }
        else if (masuk.charAt(a) == 'E' || masuk.charAt(a) == 'e') {
        arti=15;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='1') {
            arti=1;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='2') {
            arti=2;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='3') {
            arti=3;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='4') {
            arti=4;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='5') {
            arti=5;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='6') {
            arti=6;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='7') {
            arti=7;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='8') {
            arti=8;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) =='9') {
            arti=9;
        des+=arti*pangkat(16,length-1-a);
        }
        else if(masuk.charAt(a) == '0') {
        des+=0;
        }
    }
    JOptionPane.showMessageDialog(null, "desimal ="+des);
     //konversi KE Biner
        hasil=des/2;
        do{
            sisa=des%2;
            if(sisa==1){
                bin+="1";
            }
            else if(sisa == 0)
            {
                bin+="0";
            }
            des=hasil;
            hasil=des/2;
        }
        while(hasil>=1);
        String binernya="1"+bin;
        JOptionPane.showMessageDialog(null, "biner="+binernya);
        int oktal=0;
        String kebin=binernya.toString();
        int lkebin=kebin.length();
        for(a=0;a<=lkebin-1;a++){
            if(kebin.charAt(a)=='1'){
                oktal+=pangkat(8,lkebin-a-1);
            }
            if(kebin.charAt(a)=='0'){
                oktal+=0;
            }
        }
        txthasil.setText(String.valueOf(oktal));
}
    }//GEN-LAST:event_btkonversiActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        cmboperasi.requestFocus();
        txthasil.setText("");
        txtmasuk.setText("");
    }//GEN-LAST:event_btresetActionPerformed
int pangkat(int x,int y){
int pangkat=1;
for(int a=y;a>=1;a--){
    pangkat*=x ;
}
return pangkat;
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bil_dig_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btkonversi;
    private javax.swing.JButton btreset;
    private javax.swing.JComboBox cmboperasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtmasuk;
    // End of variables declaration//GEN-END:variables

}
