/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form_himpunan.java
 *
 * Created on Feb 6, 2011, 1:39:37 PM
 */

package com.zisal.himpunan;

import javax.swing.JOptionPane;

/**
 *
 * @author FAUZI
 */
public class form_himpunan extends javax.swing.JFrame {
int totala,totalb,a,b,c;
char [] himA=new char [15];
char [] himB=new char [15];
char [] inter=new char [15];
char [] union=new char [15];
char [] difAB=new char [15];
char [] difBA=new char [15];
char [] beda=new char [15];

String SdifAB="";
String SdifBA="";
String intersection="";
    /** Creates new form form_himpunan */
    public form_himpunan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txthimA = new javax.swing.JTextField();
        txthimB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtinputA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtunion = new javax.swing.JTextField();
        txtinter = new javax.swing.JTextField();
        txtdifBA = new javax.swing.JTextField();
        txtdifAB = new javax.swing.JTextField();
        txtinputB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HIMPUNAN");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txthimA.setEditable(false);

        txthimB.setEditable(false);

        jLabel1.setText("HIMPUNAN A =");

        jLabel2.setText("HIMPUNAN B =");

        txtinputA.setText("INPUT");
        txtinputA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinputAActionPerformed(evt);
            }
        });

        jLabel3.setText("INTERSECTION (A,B) = ");

        jLabel4.setText("UNION (A,B) = ");

        jLabel5.setText("DIFFERENCE (A,B) = ");

        jLabel6.setText("DIFFERENCE (B,A) = ");

        txtunion.setEditable(false);

        txtinter.setEditable(false);

        txtdifBA.setEditable(false);

        txtdifAB.setEditable(false);

        txtinputB.setText("INPUT");
        txtinputB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinputBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txthimA, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthimB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtinputB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtinputA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtinter, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtunion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtdifAB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdifBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthimA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtinputA, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtinputB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txthimB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtunion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtdifAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdifBA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtinputAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinputAActionPerformed
    String ldata=JOptionPane.showInputDialog(null,"Masukkan panjang data himpunan A",JOptionPane.QUESTION_MESSAGE);
    String isidataA,hasildataA="";
    totala=Integer.parseInt(ldata);
    if(totala>15){
        JOptionPane.showMessageDialog(rootPane, "total data harus < 15");
        System.exit(totala);
    }
 else{
    for(b=0;b<=totala-1;b++){
        isidataA=JOptionPane.showInputDialog(null,"INDEX["+(b+1)+"]",JOptionPane.QUESTION_MESSAGE);
        himA[b]=isidataA.charAt(0);
        hasildataA+=String.valueOf(himA[b])+" ";
        txthimA.setText("{ "+hasildataA+" }");
    }
        }

    }//GEN-LAST:event_txtinputAActionPerformed

    private void txtinputBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinputBActionPerformed
    String ldata=JOptionPane.showInputDialog(null,"Masukkan panjang data himpunan B",JOptionPane.QUESTION_MESSAGE);
    String isidataB,hasildataB="";
    totalb=Integer.parseInt(ldata);
    if(totalb>15){
        JOptionPane.showMessageDialog(rootPane, "Panjang data tidak boleh>15");
        System.exit(totala);
    }
 else{
    for(b=0;b<=totalb-1;b++){
        isidataB=JOptionPane.showInputDialog(null,"INDEX["+b+"]",JOptionPane.QUESTION_MESSAGE);
        himB[b]=isidataB.charAt(0);
        hasildataB+=String.valueOf(himB[b])+" ";
        txthimB.setText("{ "+hasildataB+" }");
    }
        }
    proses();
    }//GEN-LAST:event_txtinputBActionPerformed

    void proses(){
        if(txthimA.getText()!="" && txthimB.getText()!=""){
            if(totala!=totalb){
                JOptionPane.showMessageDialog(rootPane, "panjang data himpunan A != panjang data himpunan B !!!");
            }
 else{
                intersection();
                difAB();
                difBA();
                union();
 }
        }
    }
    void intersection(){        
                for(a=0;a<=totala-1;a++){
                    for(b=0;b<=totala-1;b++){
                        if(himA[a]==himB[b]){
                        inter[a]=himA[a];
                        }
 else if(himA[a]!=himB[b]){
   beda[a]=himA[a];
 }
                    }
                    intersection+=String.valueOf(inter[a])+" ";
                    intersection=intersection.trim();
                    txtinter.setText("{ "+intersection+" }");                    
                }                                    
    }
    void difAB(){        
        for(a=0;a<=totala-1;a++){            
              if(himA[a]!=himB[a]){
                 difAB[a]=himA[a];
                 for(b=0;b<=totala-1;b++){
                  if(himA[a]==himB[b]){
                     difAB[a]=' ';
                 }
                 }
            }
            SdifAB+=String.valueOf(difAB[a])+" ";
            SdifAB=SdifAB.trim();
            txtdifAB.setText("{ "+SdifAB+" }");
        }
    }
    void difBA(){        
        for(a=0;a<=totala-1;a++){            
                if(himB[a]!=himA[a]){
                    difBA[a]=himB[a];
                    for(b=0;b<=totala-1;b++){
                        if(himB[a]==himA[b]){
                            difBA[a]=' ';
                        }
                    }
                }   
            SdifBA+=String.valueOf(difBA[a])+" ";
            SdifBA=SdifBA.trim();
            txtdifBA.setText("{ "+SdifBA+" }");
        }
    }
    void union(){
    String union="";
    union+=intersection+SdifAB+SdifBA;
    union=union.trim();
    txtunion.setText("{ "+union+" }");
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_himpunan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtdifAB;
    private javax.swing.JTextField txtdifBA;
    private javax.swing.JTextField txthimA;
    private javax.swing.JTextField txthimB;
    private javax.swing.JButton txtinputA;
    private javax.swing.JButton txtinputB;
    private javax.swing.JTextField txtinter;
    private javax.swing.JTextField txtunion;
    // End of variables declaration//GEN-END:variables

}
