/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewShape.java
 *
 * Created on Jan 28, 2012, 10:49:46 AM
 */
package com.zisal.swingmakeover.chap1;

/**
 *
 * @author fauzi
 */
public class viewShape extends javax.swing.JFrame {

    /** Creates new form viewShape */
    public viewShape() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawEllipse1 = new com.zisal.swingmakeover.chap1.drawEllipse();
        drawEllipse_REct1 = new com.zisal.swingmakeover.chap1.drawEllipse_REct();
        drawREct1 = new com.zisal.swingmakeover.chap1.drawREct();
        drawString1 = new com.zisal.swingmakeover.chap1.drawString();
        loadIcon1 = new com.zisal.swingmakeover.chap1.loadIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout drawEllipse1Layout = new javax.swing.GroupLayout(drawEllipse1);
        drawEllipse1.setLayout(drawEllipse1Layout);
        drawEllipse1Layout.setHorizontalGroup(
            drawEllipse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        drawEllipse1Layout.setVerticalGroup(
            drawEllipse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(drawEllipse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 120, 110));

        javax.swing.GroupLayout drawEllipse_REct1Layout = new javax.swing.GroupLayout(drawEllipse_REct1);
        drawEllipse_REct1.setLayout(drawEllipse_REct1Layout);
        drawEllipse_REct1Layout.setHorizontalGroup(
            drawEllipse_REct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        drawEllipse_REct1Layout.setVerticalGroup(
            drawEllipse_REct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(drawEllipse_REct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 140, 120));

        javax.swing.GroupLayout drawREct1Layout = new javax.swing.GroupLayout(drawREct1);
        drawREct1.setLayout(drawREct1Layout);
        drawREct1Layout.setHorizontalGroup(
            drawREct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        drawREct1Layout.setVerticalGroup(
            drawREct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(drawREct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 120));

        javax.swing.GroupLayout drawString1Layout = new javax.swing.GroupLayout(drawString1);
        drawString1.setLayout(drawString1Layout);
        drawString1Layout.setHorizontalGroup(
            drawString1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        drawString1Layout.setVerticalGroup(
            drawString1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(drawString1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 180, -1));

        javax.swing.GroupLayout loadIcon1Layout = new javax.swing.GroupLayout(loadIcon1);
        loadIcon1.setLayout(loadIcon1Layout);
        loadIcon1Layout.setHorizontalGroup(
            loadIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        loadIcon1Layout.setVerticalGroup(
            loadIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(loadIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 140, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new viewShape().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.zisal.swingmakeover.chap1.drawEllipse drawEllipse1;
    private com.zisal.swingmakeover.chap1.drawEllipse_REct drawEllipse_REct1;
    private com.zisal.swingmakeover.chap1.drawREct drawREct1;
    private com.zisal.swingmakeover.chap1.drawString drawString1;
    private com.zisal.swingmakeover.chap1.loadIcon loadIcon1;
    // End of variables declaration//GEN-END:variables
}
