/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form_konversi_suhu.java
 *
 * Created on Aug 4, 2011, 12:10:41 PM
 */
package com.zisal.konversisuhu;

import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author FAUZI
 */
public class form_konversi_suhu extends javax.swing.JFrame {
public Dimension ukuran_layar;
    /** Creates new form form_konversi_suhu */
    public form_konversi_suhu() {
        initComponents();
        tengah();
    }
public void tengah(){
    ukuran_layar=Toolkit.getDefaultToolkit().getScreenSize();
    setLocation(ukuran_layar.width/2-getSize().width/2, ukuran_layar.height/2-getSize().height/2);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtinput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbsuhuawal = new javax.swing.JComboBox();
        btkonversi = new javax.swing.JButton();
        txtoutput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btreset = new javax.swing.JButton();
        cmbsuhutujuan = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Temprature Processor"));

        jLabel1.setText("Suhu Awal :");

        jLabel3.setText("Tujuan :");

        cmbsuhuawal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celcius", "Reamur", "Fahrenheit", "kelvin" }));

        btkonversi.setText("konversi");
        btkonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkonversiActionPerformed(evt);
            }
        });

        txtoutput.setEditable(false);

        jLabel2.setText("Suhu Hasil :");

        btreset.setText("reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        cmbsuhutujuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celcius", "Reamur", "Fahrenheit", "kelvin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtoutput, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(txtinput, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(cmbsuhutujuan, 0, 101, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btkonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbsuhuawal, 0, 101, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbsuhuawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btkonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbsuhutujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtoutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private float celcius(float input,int tujuan){
    float output = 0;
    switch(tujuan){
        case 0:output=input;break;
        case 1:output=(float) (0.8*input);break;
        case 2:output=(float) (1.8*(input+32));break;
        case 3:output=(input+273);break;
    }
    return output;
}
private float reamur(float input,int tujuan){
    float output = 0;
    switch(tujuan){
        case 0:output=(float) (1.25*input);break;
        case 1:output=input;break;
        case 2:output=(float) (2.25*(input+32));break;
        case 3:output=(float) ((1.25*input)+273);break;
    }
    return output;
}
private float fahrenheit(float input,int tujuan){
    float output = 0;
    switch(tujuan){
        case 0:output=(float) (0.6*(input-32));break;
        case 1:output=(float) (0.4*(input-32));break;
        case 2:output=input;break;
        case 3:output=(float) ((0.6*input)+273);break;
    }
    return output;
}
private float kelvin(float input,int tujuan){
    float output = 0;
    switch(tujuan){
        case 0:output=input-273;break;
        case 1:output=input-273;break;
        case 2:output=input-273;break;
        case 3:output=input;break;
    }
    return output;
}
    private void btkonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkonversiActionPerformed
        // TODO add your handling code here:
String input=txtinput.getText();
float angkainput=Integer.parseInt(input);
int pilawal=cmbsuhuawal.getSelectedIndex();
int piltujuan=cmbsuhutujuan.getSelectedIndex();
float hasil=0;
     switch(pilawal){
        case 0:hasil=celcius(angkainput, piltujuan);break;
        case 1:hasil=reamur(angkainput, piltujuan);break;
        case 2:hasil=fahrenheit(angkainput, piltujuan);break;
        case 3:hasil=kelvin(angkainput, piltujuan);break;
    }
txtoutput.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btkonversiActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        txtinput.setText("");
        txtoutput.setText("");
        txtinput.requestFocus();
        cmbsuhuawal.setSelectedIndex(0);        
    }//GEN-LAST:event_btresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new form_konversi_suhu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btkonversi;
    private javax.swing.JButton btreset;
    private javax.swing.JComboBox cmbsuhuawal;
    private javax.swing.JComboBox cmbsuhutujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtinput;
    private javax.swing.JTextField txtoutput;
    // End of variables declaration//GEN-END:variables
}
