/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewBack.java
 *
 * Created on Jan 28, 2012, 1:44:48 PM
 */

package com.zisal.swingmakeover.chap3;

/**
 *
 * @author fauzi
 */
public class viewBack extends javax.swing.JFrame {

    /** Creates new form viewBack */
    public viewBack() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictTrans1 = new com.zisal.swingmakeover.chap3.pictTrans();
        transPanel1 = new com.zisal.swingmakeover.chap3.transPanel();
        iconTrans1 = new com.zisal.swingmakeover.chap3.iconTrans();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transPanel1.setBackground(new java.awt.Color(0, 0, 0));

        org.jdesktop.layout.GroupLayout iconTrans1Layout = new org.jdesktop.layout.GroupLayout(iconTrans1);
        iconTrans1.setLayout(iconTrans1Layout);
        iconTrans1Layout.setHorizontalGroup(
            iconTrans1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 122, Short.MAX_VALUE)
        );
        iconTrans1Layout.setVerticalGroup(
            iconTrans1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 124, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout transPanel1Layout = new org.jdesktop.layout.GroupLayout(transPanel1);
        transPanel1.setLayout(transPanel1Layout);
        transPanel1Layout.setHorizontalGroup(
            transPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transPanel1Layout.createSequentialGroup()
                .add(iconTrans1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        transPanel1Layout.setVerticalGroup(
            transPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transPanel1Layout.createSequentialGroup()
                .add(iconTrans1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout pictTrans1Layout = new org.jdesktop.layout.GroupLayout(pictTrans1);
        pictTrans1.setLayout(pictTrans1Layout);
        pictTrans1Layout.setHorizontalGroup(
            pictTrans1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pictTrans1Layout.createSequentialGroup()
                .addContainerGap()
                .add(transPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pictTrans1Layout.setVerticalGroup(
            pictTrans1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pictTrans1Layout.createSequentialGroup()
                .addContainerGap()
                .add(transPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pictTrans1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewBack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.zisal.swingmakeover.chap3.iconTrans iconTrans1;
    private com.zisal.swingmakeover.chap3.pictTrans pictTrans1;
    private com.zisal.swingmakeover.chap3.transPanel transPanel1;
    // End of variables declaration//GEN-END:variables

}
