/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * aBOUT.java
 *
 * Created on Jun 19, 2011, 10:05:33 PM
 */

package com.zisal.turingmachine;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author FAUZI
 */
public class aBOUT extends javax.swing.JFrame {
public Dimension ukuran_layar;
    /** Creates new form aBOUT */
    public aBOUT() {
        initComponents();
        tengah();
        //music();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tulisan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About This Software");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kelompok_BAPK/BAPK_ABOUT.png"))); // NOI18N
        getContentPane().add(gambar, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel5.setText("xaxioza.wordpress.com");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel4.setText("fauzi.knightmaster.achmad@gmail.com");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, -1));

        tulisan.setText("Turing Machine Simulation 1.0 Version");
        jPanel1.add(tulisan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setText("Program ini digunakan untuk mensimulasikan inputan ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel3.setText("pada Natural Language dengan Mesin Turing");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel6.setText("Copyright © 2012 Achmad Fauzi dKK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void music(){
        AudioData Data;
        AudioPlayer Ap = AudioPlayer.player;
        AudioStream st;
        ContinuousAudioDataStream ulang=null;
        try {
            st=new AudioStream(new FileInputStream("Alice Deejay - Better Off Alone (Hit Radio Mix)_converted.wav"));
            Data=st.getData();
            ulang=new ContinuousAudioDataStream(Data);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
        Ap.start(ulang);
    }
    /**
    * @param args the command line arguments
    */
    public void tengah(){
        ukuran_layar=Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((ukuran_layar.width / 2) - (getSize().width / 2), (ukuran_layar.height / 2) - (getSize().height / 2));
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aBOUT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tulisan;
    // End of variables declaration//GEN-END:variables

}
