/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FORM_APP.java
 *
 * Created on Jan 19, 2012, 1:29:09 PM
 */
package com.zisal.turingmachine;

import com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author fauzi
 */
public class FORM_APP extends javax.swing.JFrame {

    /** Creates new form FORM_APP */
    public FORM_APP() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public String getM(){
        return txtM.getText();
    }
    public String [] getDataM(){
        return getM().split(" ");
    }
    public String getE(){
        return txtE.getText();
    }
    public String [] getDataE(){
        return getE().split(" ");
    }
    public String getT(){
        return txtT.getText();
    }
    public String [] getDataT(){
        return getT().split(" ");
    }
    public String getS(){
        return txtS.getText();
    }    
    public String getF(){
        return txtF.getText();
    }        
    private String [] M,E,T;
    private String S,F;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tupel = new javax.swing.JPanel();
        panel_input_tupel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        tupeljudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        F_INPUT = new javax.swing.JPanel();
        panel_Input = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtinput = new javax.swing.JTextField();
        txtoutput = new javax.swing.JTextField();
        panel_Add = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        generate = new javax.swing.JPanel();
        btGenerate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        menuCekInput = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TR SIM");
        setResizable(false);

        panel_tupel.setLayout(new java.awt.BorderLayout());

        panel_input_tupel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Input Tupel"));
        panel_input_tupel.setLayout(new java.awt.GridLayout(5, 5));

        jLabel2.setText("M :");
        panel_input_tupel.add(jLabel2);
        panel_input_tupel.add(txtM);

        jLabel3.setText("∑ :");
        panel_input_tupel.add(jLabel3);
        panel_input_tupel.add(txtE);

        jLabel4.setText("Ī :");
        panel_input_tupel.add(jLabel4);
        panel_input_tupel.add(txtT);

        jLabel5.setText("S :");
        panel_input_tupel.add(jLabel5);
        panel_input_tupel.add(txtS);

        jLabel6.setText("F :");
        panel_input_tupel.add(jLabel6);
        panel_input_tupel.add(txtF);

        panel_tupel.add(panel_input_tupel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("M : (Q, ∑, Ī, S, O, F, V)");

        javax.swing.GroupLayout tupeljudulLayout = new javax.swing.GroupLayout(tupeljudul);
        tupeljudul.setLayout(tupeljudulLayout);
        tupeljudulLayout.setHorizontalGroup(
            tupeljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tupeljudulLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        tupeljudulLayout.setVerticalGroup(
            tupeljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tupeljudulLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_tupel.add(tupeljudul, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panel_tupel, java.awt.BorderLayout.PAGE_START);

        F_INPUT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Fungsi Transisi"));
        F_INPUT.setLayout(new java.awt.BorderLayout());

        panel_Input.setLayout(new java.awt.GridLayout(2, 2));

        jLabel7.setText("Input");
        panel_Input.add(jLabel7);

        jLabel8.setText("Output");
        panel_Input.add(jLabel8);
        panel_Input.add(txtinput);
        panel_Input.add(txtoutput);

        F_INPUT.add(panel_Input, java.awt.BorderLayout.CENTER);

        panel_Add.setLayout(new java.awt.BorderLayout());

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        panel_Add.add(btAdd, java.awt.BorderLayout.CENTER);

        F_INPUT.add(panel_Add, java.awt.BorderLayout.WEST);

        generate.setLayout(new java.awt.BorderLayout());

        btGenerate.setText("Generate");
        btGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerateActionPerformed(evt);
            }
        });
        generate.add(btGenerate, java.awt.BorderLayout.CENTER);

        F_INPUT.add(generate, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(F_INPUT, java.awt.BorderLayout.PAGE_END);

        file.setMnemonic('F');
        file.setText("File");

        menuCekInput.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCekInput.setText("Cek Inputan");
        menuCekInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCekInputActionPerformed(evt);
            }
        });
        file.add(menuCekInput);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        file.add(menuExit);

        jMenuBar1.add(file);

        jMenu1.setMnemonic('T');
        jMenu1.setText("Tema");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Metal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Nimbus");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Windows");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Windows Classic");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('H');
        jMenu2.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Tentang Aplikasi Ini");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String coba="";
    public String [] getCoba(){
        String [] hasilcoba=coba.split(" ");
        return hasilcoba;
    }
    public void cek(){ 
        int P=0;
        int flag=0;
        String [] percobaan=new String[coba.length()];
        percobaan=getCoba();
        String [] checker=new String[percobaan.length];
        //pengisian checker
        for(int a=0;a<percobaan.length;a++){
            checker[a]=percobaan[a];
        }
        String [][] proses=new String[1][2];        
        proses[0][0]=getS();
        proses[0][1]=checker[P];        
/*        System.out.println(proses[0][0]);
        System.out.println(proses[0][1]);
        System.out.println(input[0][0]);
        System.out.println(input[0][1]);
        System.out.println(output[0][0]);
        System.out.println(output[0][1]);
        System.out.println(output[0][2]);
        System.out.println(checker[0]);
        System.out.println(P);
        System.out.print(checker.length);*/
        while((P>-1) && (P<checker.length)){
//                           System.out.print("masuk");
            for(int a=0;a<input.length;a++){
                if((proses[0][0].equals(input[a][0])) && (proses[0][1].equals(input[a][1]))){
                    proses[0][0]=output[a][0];
                    checker[P]=output[a][1];
                    if (output[a][2].equals("R")){
                        P++;
                        if (P>-1 && P<checker.length){
                            proses[0][1]=checker[P];             
                        }
                    }
                    else{
                        P--;
                        if (P>-1 && P<checker.length){
                            proses[0][1]=checker[P];
                        }
                    }
                flag=1;        
                }
            }
            if (flag!=1){
                boolean hasil = false;    
                JOptionPane.showMessageDialog(null, "Inputan Ditolak","Informasi",JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            }
        }
        if ((P==checker.length) || (P<0)){
        boolean hasil = true;
        JOptionPane.showMessageDialog(null, "Inputan Diterima","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        boolean hasil = false;    
        //JOptionPane.showMessageDialog(null, "Inputan ditolak","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }    
    private void btGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateActionPerformed
        // TODO add your handling code here:
        
        //all about save data
        M=getDataM();
        E=getDataE();
        T=getDataT();
        S=getS();
        F=getF();       
        
       //all about table
        String [] namaKolom={"input", "output"};                
        JTable tblTrans=new JTable(new tabel_transisi(namaKolom,inTable));
        JFrame form_transisi=new JFrame();
        form_transisi.setLocationRelativeTo(null);
        form_transisi.setTitle("FORM FUNGSI TRANSISI");
        form_transisi.setVisible(true);
        form_transisi.setSize(300,300);
        form_transisi.setLayout(new java.awt.BorderLayout());        
        form_transisi.getContentPane().add(new JScrollPane(tblTrans),java.awt.BorderLayout.CENTER);
    }//GEN-LAST:event_btGenerateActionPerformed
    int i=-1;
    public void getInput(){        
        i+=1;
        String masuk=txtinput.getText();
        String [] pisah=masuk.split(" ");       
        input[i][0]=pisah[0];
        input[i][1]=pisah[1];        
    }
    int o=-1;
    public void getOutput(){
        o+=1;
        String masuk=txtoutput.getText();
        String [] pisah=masuk.split(" ");        
        output[i][0]=pisah[0];
        output[i][1]=pisah[1];
        output[i][2]=pisah[2];        
    }    
    private String [][] input=new String[20][20];
    private String [][] output=new String[20][20];
    private Object [][] inTable=new Object[20][20];
    private int x=-1;
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here: 
        x++;
        inTable[x][0]=(Object)txtinput.getText();
        inTable[x][1]=(Object)txtoutput.getText();        
        getInput();
        getOutput();
        txtinput.setText("");
        txtoutput.setText("");
        txtinput.requestFocus();
    }//GEN-LAST:event_btAddActionPerformed

    private void menuCekInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCekInputActionPerformed
        // TODO add your handling code here:
        S=getS();
        F=getF();
        coba=JOptionPane.showInputDialog(null,"masukkan data yang akan dicek","STRING COBA",JOptionPane.QUESTION_MESSAGE);
        cek();
    }//GEN-LAST:event_menuCekInputActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
        UIManager.setLookAndFeel(new MetalLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "kesalahan pada sistem");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try{
        UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "kesalahan pada sistem");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try{
        UIManager.setLookAndFeel(new WindowsLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "kesalahan pada sistem");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try{
        UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "kesalahan pada sistem");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new aBOUT().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FORM_APP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel F_INPUT;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btGenerate;
    private javax.swing.JMenu file;
    private javax.swing.JPanel generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem menuCekInput;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JPanel panel_Add;
    private javax.swing.JPanel panel_Input;
    private javax.swing.JPanel panel_input_tupel;
    private javax.swing.JPanel panel_tupel;
    private javax.swing.JPanel tupeljudul;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtS;
    private javax.swing.JTextField txtT;
    private javax.swing.JTextField txtinput;
    private javax.swing.JTextField txtoutput;
    // End of variables declaration//GEN-END:variables
}
